export const GoStat1 = require("./GOSTAT1.png");
export const GoStat2 = require("./GOSTAT2.png");
export const GoStat3 = require("./GOSTAT3.png");
export const GoStat4 = require("./GOSTAT4.png");
export const GoStat5 = require("./GOSTAT5.png");
export const GoStat6 = require("./GOSTAT6.png");
export const GoStat7 = require("./GOSTAT7.png");
export const GoStat8 = require("./GOSTAT8.png");
export const GoStat9 = require("./GOSTAT9.png");
export const GoStat10 = require("./GOSTAT10.png");
export * as MyNutrition1 from "./MYNUTRITION1.png";
export * as MyNutrition2 from "./MYNUTRITION2.png";
export * as MyNutrition3 from "./MYNUTRITION3.png";
export * as MyNutrition4 from "./MYNUTRITION4.png";
export * as MyNutrition5 from "./MYNUTRITION5.png";
export * as GoDo1 from "./GODO1.png";
export * as GoDo2 from "./GODO2.png";
export * as GoDo3 from "./GODO3.png";
export * as GoDo4 from "./GODO4.png";
export * as GoDo5 from "./GODO5.png";
export * as GoDo6 from "./GODO6.png";
export * as Staty1 from "./STATY1.png";
export * as Staty2 from "./STATY2.png";
export * as Staty3 from "./STATY3.png";
export * as Staty4 from "./STATY4.png";
export * as Staty5 from "./STATY5.png";
